{% set version = "0.2.0" %}

package:
  name: jinja2-time
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jinja2-time/jinja2-time-{{ version }}.tar.gz
  sha256: d14eaa4d315e7688daa4969f616f226614350c48730bfa1692d2caebd8c90d40
  patches:
    # remove after https://github.com/hackebrot/jinja2-time/pull/19 (or similar)
    - 0000-replace-replace-shift.patch

build:
  noarch: python
  number: 4
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - arrow
    - jinja2
    - python >={{ python_min }}

test:
  imports:
    - jinja2_time
  source_files:
    - tests
  requires:
    - freezegun
    - pytest-cov
    - python {{ python_min }}
  commands:
    - cd tests && pytest -vv --cov jinja2_time --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 100

about:
  home: https://github.com/hackebrot/jinja2-time
  license: MIT
  license_file: LICENSE
  summary: Jinja2 Extension for Dates and Times

extra:
  recipe-maintainers:
    - bollwyvl
